baseURL = "https://blog.grew.cc/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh"
title = "Tom's Blog"
copyright = "Tom Almighty"
theme = "diary"
# googleAnalytics = "UA-123-45"
hasCJKLanguage = true
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "witchhazel"
    tabWidth = 4
[markup.goldmark.renderer]
    unsafe = true
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
subtitle = "Life is a Battle!"
favicon = "/favicon.ico"
enableReadingTime=true
enableAutoDarkMode=true
# è¯„è®ºç³»ç»Ÿ
enableGitalk = false
enableGiscus = false
walineServer = "https://waline.grew.cc"
# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = ""
# è‡ªå®šä¹‰ GitHub Stats Card URL
githubStatsBaseURL = "https://gh-card.grew.cc"
fancybox = true
# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = false
title = "My Blog" # will set 'og:site_name'
description = "è®°å½•ç”Ÿæ´» | å­¦ä¹ "  # will set 'og:description'

[params.gitalk]
  owner = ""
  repo = ""
  client_id = ""
  client_secret = ""
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"


# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="tom2almighty/giscus"
    data_repo_id="R_kgDOMhXXdQ"    
    data_category="Announcements"
    data_category_id="DIC_kwDOMhXXdc4Chgn1"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="zh-CN"
    crossorigin="anonymous"

[[menu.main]]
url = "/posts"
name = "ğŸ’¼ å½’æ¡£"
weight = 1

[[menu.main]]
url = "/categories"
name = "ğŸ—‚ åˆ†ç±»"
weight = 2

[[menu.main]]
url = "/tags"
name = "ğŸ· æ ‡ç­¾"
weight = 3

[[menu.main]]
url = "/links"
name = "ğŸ”— é“¾æ¥"
weight = 4
[[menu.main]]
url = "/about"
name = "ğŸ¯ å…³äº"
weight = 5

[[menu.main]]
url = "/search"
name = "ğŸ” æœç´¢"
weight = 6

[[menu.main]]
url = "/posterwall"
name = "ğŸ¬ è§‚å½±"
weight = 7